# Generated by Django 2.0 on 2018-06-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Absenteeism', '0003_auto_20180625_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date',
            field=models.DateField(),
        ),
    ]
