# Generated by Django 2.0 on 2018-06-25 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Absenteeism', '0004_auto_20180625_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date',
            field=models.DateField(default=datetime.date(2018, 6, 25)),
        ),
    ]
