# Generated by Django 2.0 on 2018-06-26 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Absenteeism', '0006_auto_20180625_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
    ]
