# Generated by Django 2.0 on 2018-07-06 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Absenteeism', '0009_person_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desig', models.CharField(choices=[('--select--', '--select--'), ('Supervisor', 'Supervisor'), ('TeamLeader', 'TeamLeader'), ('Senior Operator', 'Senior Operator'), ('Skilled Operator', 'Skilled Operator'), ('Semi-Skilled Operator', 'Semi-Skilled Operator'), ('Un-Skilled Operator', 'Un-Skilled Operator'), ('Helper', 'Helper'), ('Trainee', 'Trainee')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
