# Generated by Django 2.0 on 2018-07-07 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Absenteeism', '0010_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_operations', models.CharField(max_length=50)),
                ('operation_desc', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Operat',
            },
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('25%', '25%'), ('50%', '50%'), ('75%', '75%'), ('100%', '100%')], max_length=50)),
                ('skill_desc', models.CharField(max_length=1500)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scale_matrix.Operat')),
                ('use', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Absenteeism.Person')),
            ],
        ),
    ]
