# Generated by Django 2.0 on 2018-07-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale_matrix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operat',
            name='operation_desc',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='scale',
            name='skill_desc',
            field=models.TextField(max_length=1500),
        ),
    ]
