# Generated by Django 2.0 on 2018-07-07 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scale_matrix', '0002_auto_20180707_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scale',
            name='use',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Absenteeism.Person'),
        ),
    ]
