# Generated by Django 2.0 on 2018-07-09 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scale_matrix', '0003_auto_20180707_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='operat',
            name='opt_weightage',
            field=models.IntegerField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scale',
            name='use',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
