# Generated by Django 2.0 on 2018-07-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale_matrix', '0004_auto_20180709_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operat',
            name='opt_weightage',
            field=models.IntegerField(),
        ),
    ]
