# Generated by Django 2.0 on 2018-07-09 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scale_matrix', '0005_auto_20180709_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scale',
            name='use',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
