# Generated by Django 2.0 on 2018-07-09 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scale_matrix', '0006_auto_20180709_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operat',
            options={},
        ),
    ]
