# Generated by Django 2.0 on 2018-07-20 18:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('waiting', models.CharField(max_length=5)),
                ('setting', models.CharField(max_length=5)),
                ('breakdown', models.CharField(max_length=5)),
                ('power_failure', models.CharField(max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('machine_issue', models.CharField(max_length=5)),
                ('quality_issue', models.CharField(max_length=5)),
                ('trims_issue', models.CharField(max_length=5)),
                ('others', models.CharField(max_length=5)),
                ('delay_start', models.CharField(max_length=5)),
                ('demo', models.CharField(max_length=5)),
                ('learning', models.CharField(max_length=5)),
                ('full_swing', models.CharField(max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('serial_no', models.CharField(max_length=10)),
                ('hourly_achieved', models.IntegerField(default=0)),
                ('hourly_running_ticket_no', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('rework_ticket_no', models.CharField(max_length=10)),
                ('repair_ticket_no', models.CharField(max_length=10)),
                ('finish_return_ticket_no', models.CharField(max_length=10)),
                ('cutting_defects_ticket_no', models.CharField(max_length=10)),
                ('cutting_missing_ticket_no', models.CharField(max_length=10)),
                ('holding_ticket_no', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
