# Generated by Django 2.0 on 2018-07-06 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Absenteeism', '0010_employee'),
        ('leave_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Absenteeism.Employee'),
            preserve_default=False,
        ),
    ]
