# Generated by Django 2.0 on 2018-07-07 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave_calendar', '0002_leaveapplication_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Absenteeism.Employee'),
        ),
    ]
