# Generated by Django 2.0 on 2018-07-09 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave_calendar', '0003_auto_20180707_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='no_of_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Absenteeism.Employee'),
        ),
    ]
