# Generated by Django 2.0 on 2018-07-10 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave_calendar', '0004_auto_20180709_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='leave_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Absenteeism.Employee'),
        ),
    ]
