# Generated by Django 2.0 on 2018-07-10 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave_calendar', '0005_auto_20180710_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_percent', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='leave_percnt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leave_calendar.LeavePercentage'),
        ),
    ]
